"""模拟用户数据。"""

from langgraph_sdk import Auth

MOCK_USER: dict[str, Auth.types.MinimalUserDict] = {
    "admin": {
        "identity": "admin",
        "display_name": "管理员",
        "permissions": [
            "assistants:create",
            "assistants:read",
            "assistants:update",
            "assistants:delete",
            "assistants:search",
            "threads:create",
            "threads:read",
            "threads:update",
            "threads:delete",
            "threads:search",
            "threads:create_run",
            "crons:create",
            "crons:read",
            "crons:update",
            "crons:delete",
            "crons:search",
            "store:put",
            "store:get",
            "store:search",
            "store:delete",
            "store:list_namespaces",
        ],
    },
    "user_1": {
        "identity": "user_id_001",
        "display_name": "铁锤",
        "permissions": [
            "assistants:read",
            "assistants:search",
            "threads:create",
            "threads:read",
            "threads:update",
            "threads:delete",
            "threads:search",
            "threads:create_run",
            "store:put",
            "store:get",
            "store:search",
            "store:delete",
            "store:list_namespaces",
        ],
    },
    "user_2": {
        "identity": "user_id_002",
        "display_name": "丧彪",
        "permissions": [
            "assistants:read",
            "assistants:search",
            "threads:create",
            "threads:read",
            "threads:update",
            "threads:delete",
            "threads:search",
            "threads:create_run",
            "store:put",
            "store:get",
            "store:search",
            "store:delete",
            "store:list_namespaces",
        ],
    },
}
